### ISSUE TITLE
Generating the web view fails

### ISSUE THREAD

**Issue by prologic** [geek1011/repogen#4]
I'm not familiar with your codebase to understand this:

```
Warning: error generating index, index will be generated client-side on every page load
```

Am I missing something?

**Comment by pgaskin** [comment]
The search for the web interface is done client-side, but you can pre-generate the index with repogen if you have nodejs installed.

**Comment by prologic** [comment]
> The search for the web interface is done client-side, but you can pre-generate the index with repogen if you have nodejs installed.

I guess I don't understand what this means "client-side" and generate what with `node`? What doesn't the tool just do this?

**Comment by pgaskin** [comment]
The search is run in the web browser so the repository can be hosted on anything which can serve files as-is. As such, it's written in JavaScript, not Go. There are Go runtimes for JavaScript such as otto, but it doesn't support the required features. Another option would be to embed V8 with CGO, but I don't want to add that to the binary, as it would increase the size significantly.

I'm planning on doing a rewrite of this later this year, and the rewrite will probably avoid having any external dependencies like this.
