### ISSUE TITLE
Incorrect domain

### ISSUE THREAD

**Issue by okalachev** [geek1011/repogen#5]
Deployed a Debian repo to a custom domain using GitHub pages. And there is incorrect URL in 'installation' section:

<img width="609" alt="Screenshot 2021-01-30 at 11 38 59" src="https://user-images.githubusercontent.com/1683279/106351834-bf3bb880-62ef-11eb-8b50-eb16a314aff3.png">

Link: http://packages.coex.tech/packages/buster/.

How it can be fixed?

**Comment by okalachev** [comment]
Found the bug, will send a PR.

**Comment by okalachev** [comment]
#6, @pgaskin, please, have a look.

**Comment by pgaskin** [comment]
Thanks!
